# https://github.com/marketplace/actions/release-drafter
# https://github.com/release-drafter/release-drafter#configuration

name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.*\))?!?:/i'
  - label: 'bug'
    title:
      - '/^fix(\(.*\))?!?:/i'
  - label: 'documentation'
    title:
      - '/^docs(\(.*\))?!?:/i'
  - label: 'maintenance'
    title:
      - '/^(chore|build|ci|refactor|perf|style|test)(\(.*\))?!?:/i'
categories:
  - title: '✨ Features'
    labels: 
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels: 
      - 'bug'
  - title: '📝 Documentation'
    labels: 
      - 'documentation'
  - title: '🛠️ Maintenance'
    labels: 
      - 'maintenance'
template: |
  ## What's New/Changed in this Release

  $CHANGES
