blank_issues_enabled: false # Set to true to allow users to create blank issues without a template.
contact_links:
  - name: Ask a question / Discussion
    url: https://github.com/Bleala/Postfix-DOCKERIZED/discussions/new
    about: Please ask questions or start discussions here.